# Generated by Django 3.2.16 on 2023-01-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='np1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='np2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='np3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='npa',
            field=models.IntegerField(),
        ),
    ]
